spring:
  datasource:
    url: ${DEV_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DEV_DATABASE_USER}
    password: ${DEV_DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${DEV_SUPABASE_URL}/auth/v1/.well-known/jwks.json

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: false

# Frontend Configuration (CORS 허용 오리진)
frontend:
  url: ${DEV_FRONTEND_URL}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

#OpenTelemetry : off
otel:
  sdk:
    disabled: true
management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
