spring:
  datasource:
    url: ${STAGING_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${STAGING_DATABASE_USER}
    password: ${STAGING_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: false

# Frontend Configuration (CORS 허용 오리진)
frontend:
  url: ${STAGING_FRONTEND_URL}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

#OpenTelemetry : off
otel:
  sdk:
    disabled: true
management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
