spring:
  datasource:
    url: ${PROD_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PROD_DATABASE_USER}
    password: ${PROD_DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${PROD_SUPABASE_URL}/auth/v1/.well-known/jwks.json

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    enabled: false # /v3/api-docs API
  swagger-ui:
    enabled: false # /swagger-ui.html

# Frontend Configuration (CORS 허용 오리진)
frontend:
  url: ${PROD_FRONTEND_URL}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

#OpenTelemetry : off
otel:
  sdk:
    disabled: true
management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
