spring:
  datasource:
    url: ${db-url}
    driver-class-name: org.postgresql.Driver
    username: ${db-username}
    password: ${db-password}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${supabase-url}/auth/v1/.well-known/jwks.json

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Frontend Configuration (CORS 허용 오리진)
frontend:
  url: http://localhost:3000


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

#OpenTelemetry : off
otel:
  sdk:
    disabled: true
management:
  otlp:
    metrics:
      export:
        enabled: false
    logging:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
