package org.sscc.ssccopsserver.domain.operation.entity;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import org.sscc.ssccopsserver.domain.member.entity.MemberEntity;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

/*
 * sub_work_aprv_vote(하위 업무 승인 투표) — 정족수 유형의 하위 업무에 운영진이 던지는 찬반 한 표.
 *
 * 데이터사전은 부모를 sub_work_aprv_id(하위 업무 승인)로 적고 있으나 sub_work_id로 바꿨다.
 * sub_work_aprv 행은 승인·완료(TR-03)가 일어나는 순간에만 저장되는데 투표는 그보다 먼저
 * 일어나므로, 사전대로면 투표 시점에 가리킬 부모 행이 없다. 투표는 '승인 건'이 아니라
 * '하위 업무'에 달린다 (#47).
 *
 * aprv_seqno(승인 순번)는 회차다. 반려 → 보완 → 재검토요청으로 다시 올라온 건의 이전 찬성은
 * 새 계획에 대한 동의가 아니므로 집계에서 빠져야 하는데, 이력은 지우지 않는다(POL-004).
 * 그래서 지우는 대신 회차로 나눈다. 회차 값은 저장 컬럼 없이 sub_work_stts_hstry의
 * 검토(REVIEW) 진입 횟수에서 파생한다 — 하위 업무에 또 하나의 갱신 대상 컬럼을 두지 않기 위해서다.
 *
 * agre_yn은 NULL을 허용한다(기권 자리). 지금은 화면에 기권 버튼이 없어 항상 값이 있다.
 * vote_dt는 데이터사전에서 NULL 허용이었으나 NOT NULL로 바꿨다 — 시각 없는 투표는 없다.
 * 값은 DB 기본값이 아니라 주입된 Clock이 채운다(sub_work_stts_hstry.chg_dt와 같은 이유).
 *
 * 1인 1표는 uk_sub_work_aprv_vote가 강제한다. 선조회만으로는 동시 요청을 막지 못한다.
 *
 * 주의: prod도 ddl-auto가 update이므로(정식 버전 전까지 한시적) 이 선언은 배포 때 반영된다.
 * update는 추가만 하고 삭제·이름 변경·타입 변경은 반영하지 않으니, 아래 DDL은 그런 변경이
 * 필요할 때와 정식 버전에서 ddl-auto를 none으로 되돌린 뒤를 위한 기준으로 남긴다.
 *   CREATE TABLE sub_work_aprv_vote (
 *       aprv_vote_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *       sub_work_id   BIGINT    NOT NULL REFERENCES sub_work (sub_work_id),
 *       mbr_id        BIGINT    NOT NULL REFERENCES mbr (mbr_id),
 *       aprv_seqno    SMALLINT  NOT NULL,
 *       agre_yn       BOOLEAN,
 *       vote_dt       TIMESTAMP NOT NULL,
 *       CONSTRAINT uk_sub_work_aprv_vote UNIQUE (sub_work_id, aprv_seqno, mbr_id)
 *   );
 *   CREATE INDEX idx_sub_work_aprv_vote_sub_work ON sub_work_aprv_vote (sub_work_id, aprv_seqno);
 */
@Entity
@Table(
        name = "sub_work_aprv_vote",
        uniqueConstraints =
                @UniqueConstraint(
                        name = "uk_sub_work_aprv_vote",
                        columnNames = {"sub_work_id", "aprv_seqno", "mbr_id"}),
        indexes =
                @Index(
                        name = "idx_sub_work_aprv_vote_sub_work",
                        columnList = "sub_work_id, aprv_seqno"))
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class SubWorkApprovalVoteEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "aprv_vote_id")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "sub_work_id", nullable = false, updatable = false)
    private SubWorkEntity subWork;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "mbr_id", nullable = false, updatable = false)
    private MemberEntity voter;

    // 승인 회차. 검토(REVIEW)에 들어갈 때마다 1씩 올라가며 집계는 현재 회차만 센다
    @Column(name = "aprv_seqno", nullable = false, updatable = false)
    private int approvalSequence;

    // TRUE=찬성 · FALSE=반대 · NULL=기권(미구현)
    @Column(name = "agre_yn")
    private Boolean agreed;

    @Column(name = "vote_dt", nullable = false)
    private Instant votedAt;

    public static SubWorkApprovalVoteEntity cast(
            SubWorkEntity subWork,
            MemberEntity voter,
            int approvalSequence,
            VoteChoice choice,
            Instant votedAt) {
        return new SubWorkApprovalVoteEntity(
                null, subWork, voter, approvalSequence, choice.agreed(), votedAt);
    }

    /*
     * 같은 회차에 다시 투표하면 새 표를 만들지 않고 기존 표를 바꾼다. 화면이 낙관적으로
     * 버튼을 눌러 두고 재전송하는 흐름이라 두 번째 호출을 409로 끊으면 버튼이 잠긴다.
     * 시각도 함께 갱신한다 — 마지막 의사표시가 언제였는지가 남아야 한다.
     */
    public void changeVote(VoteChoice choice, Instant votedAt) {
        this.agreed = choice.agreed();
        this.votedAt = votedAt;
    }

    public VoteChoice choice() {
        return agreed == null ? null : VoteChoice.of(agreed);
    }
}
