-- ============================================================================
-- V15 — 콘텐츠 도메인 테이블 넷 (cntnt_page · cntnt_page_hstry · cntnt_post · cntnt_post_hstry)
--        + file_rfrnc.trgt_se_cd CHECK에 CONTENT_POST 추가
-- ============================================================================
-- ssccops#381 (Epic ssccops#378) · ADR-0038. 홍보국이 개발자 없이 www의 소개·연혁·활동
-- 아카이브를 쓰고 고치는 자리다 — 어드민이 쓰고 익명(/public/v1/**)이 읽는다.
--
-- **페이지와 포스트는 다른 테이블이다.** 페이지(소개·연혁·운영진)는 slug로 찾는 단건이고
-- 포스트(활동 아카이브)는 분류·활동일·요약·표지가 있는 목록이다. 한 테이블로 합치면 그 넷이
-- 페이지 행에서 전부 NULL이고, 목록 질의마다 «페이지가 아닌 것»이라는 필터가 붙는다 —
-- 템플릿을 폼의 플래그가 아니라 form_tmpl로 나눈 #142와 같은 판단이다.
--
-- **이력 테이블은 변경 뒤 전체 스냅샷이다**(bfr_/aftr_ 쌍이 아니다). 개인정보 처리방침 같은
-- 페이지의 «그때 무엇이 게시돼 있었나»가 법적으로 필요한 값이고, 한 행이 한 시점의 본문 전체를
-- 들고 있어야 diff 없이 그대로 읽힌다. 전 컬럼 updatable = false(엔티티)이며 지우는 경로가 없다.
--
-- 본문(mtxt)은 마크다운 원문 그대로다 — 서버는 길이 상한만 보고 파싱·검증은 화면이 한다
-- (ADR-0038 «본문 포맷 A»). 행사 본문(event.mtxt_cn)과 같은 파이프라인이다.
--
-- 표준 단어(데이터사전): 콘텐츠 cntnt · 페이지 page · 게시 pub · 요약 smry · 표지 cover ·
-- 제목 ttl · 본문 mtxt · 상태 stts · 코드 cd · 일시 dt · 일자 ymd · 분류 clsf · 변경 chg ·
-- 회원 mbr · 수정 mdfcn · 파일 file · 등록 reg · 활동 actv.
--
-- 제약·식별자는 읽을 수 있는 이름으로 짓고 IF NOT EXISTS로 둔다(V5의 판단 그대로 — local은
-- ddl-auto: update라 Hibernate가 먼저 만들 수 있고, 그때 두 번 만들지 않는다).
--
-- CHECK 제약의 값 목록은 ContentPublishStatus · ContentCategory · FileTargetType의 사본이다 —
-- 정본은 enum이고 FlywayMigrationValidateTest.checkConstraintsMatchTheirEnums가 대조한다(#443).
-- ============================================================================

-- ── cntnt_page ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."cntnt_page" (
    "page_id" bigint NOT NULL,
    -- 공개 주소의 식별자. 소문자·숫자·하이픈만(ContentSlug) — 숫자 id는 훑을 수 있어 쓰지 않는다
    "slug" character varying(80) NOT NULL,
    "ttl" character varying(200) NOT NULL,
    -- 마크다운 원문. 길이 상한은 서버(ContentBody.MAX_LENGTH)가 본다
    "mtxt" "text" NOT NULL,
    -- DRAFT · PUBLISHED (ContentPublishStatus). 익명은 PUBLISHED만 본다
    "pub_stts_cd" character varying(20) NOT NULL,
    -- 마지막으로 게시한 시각. 게시 취소하면 비운다
    "pub_dt" timestamp(6) with time zone,
    -- 마지막 수정자. 요청 본문이 아니라 @CurrentMember로 채운다
    "mdfcn_mbr_id" bigint NOT NULL,
    "reg_dt" timestamp(6) with time zone NOT NULL,
    "mdfcn_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "cntnt_page_pub_stts_cd_check"
        CHECK ((("pub_stts_cd")::"text" = ANY ((ARRAY[
            'DRAFT'::character varying,
            'PUBLISHED'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'cntnt_page'
                      AND "column_name" = 'page_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."cntnt_page"
            ALTER COLUMN "page_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."cntnt_page_page_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'cntnt_page_pkey') THEN
        ALTER TABLE ONLY "public"."cntnt_page"
            ADD CONSTRAINT "cntnt_page_pkey" PRIMARY KEY ("page_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_cntnt_page_slug') THEN
        ALTER TABLE ONLY "public"."cntnt_page"
            ADD CONSTRAINT "uk_cntnt_page_slug" UNIQUE ("slug");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_page_mdfcn_mbr') THEN
        ALTER TABLE ONLY "public"."cntnt_page"
            ADD CONSTRAINT "fk_cntnt_page_mdfcn_mbr"
            FOREIGN KEY ("mdfcn_mbr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

-- ── cntnt_page_hstry ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."cntnt_page_hstry" (
    "page_hstry_id" bigint NOT NULL,
    "page_id" bigint NOT NULL,
    "ttl" character varying(200) NOT NULL,
    "mtxt" "text" NOT NULL,
    "pub_stts_cd" character varying(20) NOT NULL,
    "chg_mbr_id" bigint NOT NULL,
    "chg_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "cntnt_page_hstry_pub_stts_cd_check"
        CHECK ((("pub_stts_cd")::"text" = ANY ((ARRAY[
            'DRAFT'::character varying,
            'PUBLISHED'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'cntnt_page_hstry'
                      AND "column_name" = 'page_hstry_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."cntnt_page_hstry"
            ALTER COLUMN "page_hstry_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."cntnt_page_hstry_page_hstry_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'cntnt_page_hstry_pkey') THEN
        ALTER TABLE ONLY "public"."cntnt_page_hstry"
            ADD CONSTRAINT "cntnt_page_hstry_pkey" PRIMARY KEY ("page_hstry_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_page_hstry_page') THEN
        ALTER TABLE ONLY "public"."cntnt_page_hstry"
            ADD CONSTRAINT "fk_cntnt_page_hstry_page"
            FOREIGN KEY ("page_id") REFERENCES "public"."cntnt_page"("page_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_page_hstry_chg_mbr') THEN
        ALTER TABLE ONLY "public"."cntnt_page_hstry"
            ADD CONSTRAINT "fk_cntnt_page_hstry_chg_mbr"
            FOREIGN KEY ("chg_mbr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

-- 이력 조회는 언제나 페이지 하나를 축으로 한다 (FK에 인덱스가 자동으로 붙지 않는다 · DB-17)
CREATE INDEX IF NOT EXISTS "idx_cntnt_page_hstry_page_id"
    ON "public"."cntnt_page_hstry" ("page_id");

-- ── cntnt_post ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."cntnt_post" (
    "post_id" bigint NOT NULL,
    "slug" character varying(80) NOT NULL,
    -- ACADEMIC · EVENT · NEWS (ContentCategory). 익명 목록의 category 필터가 이 값이다
    "cntnt_clsf_cd" character varying(20) NOT NULL,
    "ttl" character varying(200) NOT NULL,
    -- 목록 카드에 쓰는 한두 줄. 없으면 NULL
    "smry" character varying(300),
    "mtxt" "text" NOT NULL,
    -- 활동일. 익명 목록의 정렬 키(최신 활동 먼저)라 NOT NULL이다 — 게시일과 다르다
    "actv_ymd" date NOT NULL,
    -- 이 포스트가 갈무리한 행사. from-event로 만들면 채워지고 손으로 지울 수 있다
    "event_id" bigint,
    -- 표지. 갤러리(file_rfrnc · CONTENT_POST) 중 한 장이며 그 행이 지워지면 함께 비운다
    "cover_file_id" bigint,
    "pub_stts_cd" character varying(20) NOT NULL,
    "pub_dt" timestamp(6) with time zone,
    "mdfcn_mbr_id" bigint NOT NULL,
    "reg_dt" timestamp(6) with time zone NOT NULL,
    "mdfcn_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "cntnt_post_cntnt_clsf_cd_check"
        CHECK ((("cntnt_clsf_cd")::"text" = ANY ((ARRAY[
            'ACADEMIC'::character varying,
            'EVENT'::character varying,
            'NEWS'::character varying])::"text"[]))),
    CONSTRAINT "cntnt_post_pub_stts_cd_check"
        CHECK ((("pub_stts_cd")::"text" = ANY ((ARRAY[
            'DRAFT'::character varying,
            'PUBLISHED'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'cntnt_post'
                      AND "column_name" = 'post_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."cntnt_post"
            ALTER COLUMN "post_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."cntnt_post_post_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'cntnt_post_pkey') THEN
        ALTER TABLE ONLY "public"."cntnt_post"
            ADD CONSTRAINT "cntnt_post_pkey" PRIMARY KEY ("post_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_cntnt_post_slug') THEN
        ALTER TABLE ONLY "public"."cntnt_post"
            ADD CONSTRAINT "uk_cntnt_post_slug" UNIQUE ("slug");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_post_event') THEN
        ALTER TABLE ONLY "public"."cntnt_post"
            ADD CONSTRAINT "fk_cntnt_post_event"
            FOREIGN KEY ("event_id") REFERENCES "public"."event"("event_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_post_cover_file') THEN
        ALTER TABLE ONLY "public"."cntnt_post"
            ADD CONSTRAINT "fk_cntnt_post_cover_file"
            FOREIGN KEY ("cover_file_id") REFERENCES "public"."file_rfrnc"("file_rfrnc_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_post_mdfcn_mbr') THEN
        ALTER TABLE ONLY "public"."cntnt_post"
            ADD CONSTRAINT "fk_cntnt_post_mdfcn_mbr"
            FOREIGN KEY ("mdfcn_mbr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

-- 익명 목록의 질의 모양 그대로다: 게시본을 분류로 걸러 활동일 역순 (커서 = actv_ymd, post_id)
CREATE INDEX IF NOT EXISTS "idx_cntnt_post_pub_list"
    ON "public"."cntnt_post" ("pub_stts_cd", "cntnt_clsf_cd", "actv_ymd" DESC, "post_id" DESC);

-- ── cntnt_post_hstry ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."cntnt_post_hstry" (
    "post_hstry_id" bigint NOT NULL,
    "post_id" bigint NOT NULL,
    "cntnt_clsf_cd" character varying(20) NOT NULL,
    "ttl" character varying(200) NOT NULL,
    "smry" character varying(300),
    "mtxt" "text" NOT NULL,
    "actv_ymd" date NOT NULL,
    "pub_stts_cd" character varying(20) NOT NULL,
    "chg_mbr_id" bigint NOT NULL,
    "chg_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "cntnt_post_hstry_cntnt_clsf_cd_check"
        CHECK ((("cntnt_clsf_cd")::"text" = ANY ((ARRAY[
            'ACADEMIC'::character varying,
            'EVENT'::character varying,
            'NEWS'::character varying])::"text"[]))),
    CONSTRAINT "cntnt_post_hstry_pub_stts_cd_check"
        CHECK ((("pub_stts_cd")::"text" = ANY ((ARRAY[
            'DRAFT'::character varying,
            'PUBLISHED'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'cntnt_post_hstry'
                      AND "column_name" = 'post_hstry_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."cntnt_post_hstry"
            ALTER COLUMN "post_hstry_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."cntnt_post_hstry_post_hstry_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'cntnt_post_hstry_pkey') THEN
        ALTER TABLE ONLY "public"."cntnt_post_hstry"
            ADD CONSTRAINT "cntnt_post_hstry_pkey" PRIMARY KEY ("post_hstry_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_post_hstry_post') THEN
        ALTER TABLE ONLY "public"."cntnt_post_hstry"
            ADD CONSTRAINT "fk_cntnt_post_hstry_post"
            FOREIGN KEY ("post_id") REFERENCES "public"."cntnt_post"("post_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_cntnt_post_hstry_chg_mbr') THEN
        ALTER TABLE ONLY "public"."cntnt_post_hstry"
            ADD CONSTRAINT "fk_cntnt_post_hstry_chg_mbr"
            FOREIGN KEY ("chg_mbr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_cntnt_post_hstry_post_id"
    ON "public"."cntnt_post_hstry" ("post_id");

-- ── file_rfrnc.trgt_se_cd CHECK 넓히기 ─────────────────────────────────────
-- 갤러리는 새 테이블이 아니라 file_rfrnc(trgt_se_cd = 'CONTENT_POST', trgt_id = post_id)다 —
-- #220이 그 테이블을 도메인 중립으로 연 이유가 이것이다. enum에 값을 더하면 제약도 함께
-- 넓힌다(V13이 두 번째로 샌 결함이고 이번이 그 규칙의 첫 정상 적용이다). V13과 같이 제약을
-- 이름이 아니라 컬럼으로 찾아 지운다.
DO $$
DECLARE
    stale_constraint text;
BEGIN
    IF to_regclass('public.file_rfrnc') IS NULL THEN
        RETURN;
    END IF;

    FOR stale_constraint IN
        SELECT c.conname
          FROM pg_constraint c
          JOIN pg_attribute a
            ON a.attrelid = c.conrelid
           AND a.attnum = ANY (c.conkey)
         WHERE c.conrelid = 'public.file_rfrnc'::regclass
           AND c.contype = 'c'
           AND a.attname = 'trgt_se_cd'
           AND cardinality(c.conkey) = 1
    LOOP
        EXECUTE format(
            'ALTER TABLE "public"."file_rfrnc" DROP CONSTRAINT %I', stale_constraint);
    END LOOP;

    ALTER TABLE "public"."file_rfrnc"
        ADD CONSTRAINT "file_rfrnc_trgt_se_cd_check"
        CHECK ((("trgt_se_cd")::"text" = ANY ((ARRAY[
            'SESSION'::character varying,
            'RAG_DOCUMENT'::character varying,
            'CONTENT_POST'::character varying
        ])::"text"[])));
END $$;

-- 갤러리 조회는 (대상 구분, 대상 id)로 한다. 회차 인증사진은 대상당 1건이라 인덱스가 없었지만
-- 포스트는 여러 장이다 — uk_file_rfrnc_sesn(부분 유니크)은 SESSION에만 걸려 있어 그대로다.
CREATE INDEX IF NOT EXISTS "idx_file_rfrnc_trgt"
    ON "public"."file_rfrnc" ("trgt_se_cd", "trgt_id");
