-- ============================================================================
-- V21 — 알림 도메인 테이블 둘 (push_sbscrp · noti)
-- ============================================================================
-- ssccops#446 (Epic ssccops#163) · ADR-0045. 하위 업무의 승인 요청·승인·반려·마감이 사건이
-- 되어 받을 사람의 알림 행(noti)으로 남고, 그 사람이 등록한 브라우저(push_sbscrp)로 표준
-- Web Push(VAPID)가 간다.
--
-- **발송 이력 표는 없다.** noti 행이 «만들어졌다»의 기록이고 푸시는 최선 노력 전송이라 결과는
-- 로그(ELK)로만 남긴다(ADR-0045). 배달 통계가 필요해지면 그때 표를 더한다.
--
-- **회원이 지워지면 두 표 모두 함께 지워진다**(ON DELETE CASCADE · V9의 «본인 데이터» 규칙).
-- 구독은 그 사람의 브라우저이고 알림은 그 사람이 받은 것이라, 회원이 없어지면 뜻을 잃는 행이다.
-- 행위자 참조가 아니므로 MemberReferenceConstraints(막는 참조 표)에는 오르지 않는다 —
-- 대신 FlywayMigrationValidateTest의 «mbr을 가리키는 cascade FK» 수가 9 → 11로 는다.
--
-- pvdr_cd(제공자)는 지금 WEB_PUSH 하나다. 네이티브 앱을 내면 FCM/APNs 행이 같은 표에 다른
-- 제공자 코드로 들어온다(ADR-0045 «뒤집는다면») — 그래서 endpoint·키 컬럼 이름을 Web Push
-- 어휘(p256dh·auth)로 두되 제공자 열을 처음부터 둔다.
--
-- noti_key는 «같은 사건을 두 번 알리지 않는다»의 열쇠다. 마감 스케줄러가 매일 09:00에 돌며
-- 재기동·중복 실행에도 D-1·첫 지연일 알림이 한 번만 가야 하므로(#446 수용 기준), 키를
-- `{유형}:SUB_WORK:{id}:{마감일}`로 만들고 (mbr_id, noti_key) UNIQUE가 두 번째 INSERT를 거절한다.
-- 전이 알림(승인 요청·승인·반려)은 같은 전이가 두 번 일어날 수 있는 사건이라(반려 뒤 재요청)
-- 키가 NULL이다 — PostgreSQL의 UNIQUE는 NULL을 서로 다른 값으로 보므로 충돌하지 않는다.
--
-- 표준 단어(데이터사전 · ssccops#450): 푸시 push · 구독 sbscrp · 제공자 pvdr · 앱 app ·
-- 엔드포인트 endpt · 인증 auth · 만료 expry · 알림 noti · 유형 type · 제목 ttl · 내용 cn ·
-- 링크 lnk · 경로 path · 대상 trgt · 읽음 read · 등록 reg · 수정 upd · 코드 cd · 일시 dt.
--
-- 제약·식별자는 읽을 수 있는 이름으로 짓고 IF NOT EXISTS로 둔다(V15의 판단 그대로 — local은
-- ddl-auto: update라 Hibernate가 먼저 만들 수 있고, 그때 두 번 만들지 않는다).
--
-- CHECK 제약의 값 목록은 PushProvider · NotificationApp · NotificationType ·
-- NotificationTargetType의 사본이다 — 정본은 enum이고
-- FlywayMigrationValidateTest.checkConstraintsMatchTheirEnums가 대조한다(#443).
-- ============================================================================

-- ── push_sbscrp (푸시_구독) ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."push_sbscrp" (
    "push_sbscrp_id" bigint NOT NULL,
    "mbr_id" bigint NOT NULL,
    -- WEB_PUSH (PushProvider). FCM/APNs가 들어오면 여기서 갈린다
    "pvdr_cd" character varying(20) NOT NULL,
    -- ADMIN · LMS · WWW (NotificationApp) — 어느 앱의 서비스워커가 등록한 구독인가
    "app_cd" character varying(20) NOT NULL,
    -- 푸시 서비스가 준 capability URL. 그 자체가 비밀에 가까워 로그에 싣지 않는다
    "endpt" character varying(2000) NOT NULL,
    -- 브라우저의 P-256 공개키(base64url · 65바이트 = 87자)와 인증 비밀(16바이트 = 22자)
    "p256dh_key" character varying(255) NOT NULL,
    "auth_key" character varying(255) NOT NULL,
    -- 브라우저가 알려 준 만료. 대개 NULL이다
    "expry_dt" timestamp(6) with time zone,
    "reg_dt" timestamp(6) with time zone NOT NULL,
    "upd_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "push_sbscrp_pvdr_cd_check"
        CHECK ((("pvdr_cd")::"text" = 'WEB_PUSH'::"text")),
    CONSTRAINT "push_sbscrp_app_cd_check"
        CHECK ((("app_cd")::"text" = ANY ((ARRAY[
            'ADMIN'::character varying,
            'LMS'::character varying,
            'WWW'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'push_sbscrp'
                      AND "column_name" = 'push_sbscrp_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."push_sbscrp"
            ALTER COLUMN "push_sbscrp_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."push_sbscrp_push_sbscrp_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'push_sbscrp_pkey') THEN
        ALTER TABLE ONLY "public"."push_sbscrp"
            ADD CONSTRAINT "push_sbscrp_pkey" PRIMARY KEY ("push_sbscrp_id");
    END IF;
    -- 같은 브라우저 구독은 한 행이다. 다시 등록하면 회원·키를 갱신한다(로그인 계정이 바뀐 경우 포함)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_push_sbscrp_endpt') THEN
        ALTER TABLE ONLY "public"."push_sbscrp"
            ADD CONSTRAINT "uk_push_sbscrp_endpt" UNIQUE ("endpt");
    END IF;
    -- 회원 본인 데이터 — 회원이 지워지면 함께 지워진다 (V9 · ADR-0021)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_push_sbscrp_mbr') THEN
        ALTER TABLE ONLY "public"."push_sbscrp"
            ADD CONSTRAINT "fk_push_sbscrp_mbr"
            FOREIGN KEY ("mbr_id") REFERENCES "public"."mbr"("mbr_id") ON DELETE CASCADE;
    END IF;
END $$;

-- 발송은 «이 회원의 구독 전부»를 읽는다
CREATE INDEX IF NOT EXISTS "idx_push_sbscrp_mbr"
    ON "public"."push_sbscrp" ("mbr_id");

-- ── noti (알림) ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."noti" (
    "noti_id" bigint NOT NULL,
    "mbr_id" bigint NOT NULL,
    -- APPROVAL_REQUESTED · APPROVAL_APPROVED · APPROVAL_REJECTED · DEADLINE_DUE · DEADLINE_OVERDUE
    -- (NotificationType)
    "noti_type_cd" character varying(30) NOT NULL,
    "ttl" character varying(200) NOT NULL,
    "cn" character varying(500) NOT NULL,
    -- 어느 앱으로 보내는 알림인가(링크 경로가 그 앱의 라우트다). 1차 사건은 전부 ADMIN
    "app_cd" character varying(20) NOT NULL,
    -- 앱 안의 경로. 절대 URL은 서비스워커가 자기 origin으로 만든다 — 서버는 앱 origin을 모른다
    "lnk_path" character varying(500) NOT NULL,
    -- SUB_WORK (NotificationTargetType). FK가 없다 — 공유 링크(shr_lnk)와 같은 판단이며,
    -- 대상이 지워져도 «그때 그 알림이 갔다»는 남는다
    "trgt_type_cd" character varying(20) NOT NULL,
    "trgt_id" bigint NOT NULL,
    -- 중복 방지 키. 전이 알림은 NULL, 마감 알림은 `{유형}:SUB_WORK:{id}:{마감일}`
    "noti_key" character varying(100),
    "read_dt" timestamp(6) with time zone,
    "reg_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "noti_noti_type_cd_check"
        CHECK ((("noti_type_cd")::"text" = ANY ((ARRAY[
            'APPROVAL_REQUESTED'::character varying,
            'APPROVAL_APPROVED'::character varying,
            'APPROVAL_REJECTED'::character varying,
            'DEADLINE_DUE'::character varying,
            'DEADLINE_OVERDUE'::character varying])::"text"[]))),
    CONSTRAINT "noti_app_cd_check"
        CHECK ((("app_cd")::"text" = ANY ((ARRAY[
            'ADMIN'::character varying,
            'LMS'::character varying,
            'WWW'::character varying])::"text"[]))),
    CONSTRAINT "noti_trgt_type_cd_check"
        CHECK ((("trgt_type_cd")::"text" = 'SUB_WORK'::"text"))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'noti'
                      AND "column_name" = 'noti_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."noti"
            ALTER COLUMN "noti_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."noti_noti_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'noti_pkey') THEN
        ALTER TABLE ONLY "public"."noti"
            ADD CONSTRAINT "noti_pkey" PRIMARY KEY ("noti_id");
    END IF;
    -- 같은 사람에게 같은 키의 알림은 한 번 — 마감 스케줄러의 중복 방지 장치
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_noti_mbr_key') THEN
        ALTER TABLE ONLY "public"."noti"
            ADD CONSTRAINT "uk_noti_mbr_key" UNIQUE ("mbr_id", "noti_key");
    END IF;
    -- 회원 본인 데이터 — 회원이 지워지면 함께 지워진다 (V9 · ADR-0021)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_noti_mbr') THEN
        ALTER TABLE ONLY "public"."noti"
            ADD CONSTRAINT "fk_noti_mbr"
            FOREIGN KEY ("mbr_id") REFERENCES "public"."mbr"("mbr_id") ON DELETE CASCADE;
    END IF;
END $$;

-- 목록은 «내 알림을 최신부터 커서로»(mbr_id, noti_id desc), 배지는 «내 안 읽은 것 수»(mbr_id, read_dt)
CREATE INDEX IF NOT EXISTS "idx_noti_mbr_id_desc"
    ON "public"."noti" ("mbr_id", "noti_id" DESC);
CREATE INDEX IF NOT EXISTS "idx_noti_mbr_read"
    ON "public"."noti" ("mbr_id", "read_dt");
