-- ============================================================================
-- V23 — 알림 수신 앱 기준표 (noti_type_rcpn) + 지금 12종의 시드
-- ============================================================================
-- #535 · ssccops#465 · ADR-0047(ADR-0046을 대체한다).
--
-- **수신 앱은 코드가 아니라 이 표가 정한다.** `NotificationType`은 사건의 이름일 뿐이고
-- «어느 앱에 보이는가»는 학기마다 앱 구성이 바뀌면 따라 바뀌는 값이라, 조정이 배포가 아니라
-- 어드민 화면 조작이어야 한다(ADR-0047). 그래서 enum에 targets 필드를 두지 않았다 —
-- ADR-0046이 그 설계였고 코드가 되기 전에 대체됐다.
--
-- (noti_type_cd, app_cd) 한 쌍이 한 행이며 **유형 하나가 여러 앱**을 가리킬 수 있다.
-- 그 유형의 행이 하나도 없으면 «미등록»이고, 해석기는 그 알림 행 자신의 app_cd(= 보낸 앱)
-- 하나로 읽는다 — 새 유형을 더하며 시드를 빠뜨려도 깨지지 않게 하는 안전한 기본값이다.
--
-- ── noti_type_cd에 CHECK를 걸지 않는다 ─────────────────────────────────────
-- V21·V22가 noti.noti_type_cd에 건 CHECK는 «enum이 정본이고 제약은 사본»이라
-- FlywayMigrationValidateTest가 전수 대조한다(#443). 여기는 반대로 간다:
--
--  · 이 표는 **정책 데이터**라 유형이 늘 때마다 CHECK를 넓히는 마이그레이션이 또 필요해진다.
--    noti 쪽은 그 대가를 치를 값어치가 있다(제약이 좁으면 INSERT가 터져 알림이 유실된다).
--    여기서 좁은 제약이 막는 것은 «쓰지 않는 정책 행»뿐이고, 그 행은 아무 일도 하지 않는다.
--  · 유형을 **뺄** 때 noti 쪽은 옛 알림 행이 남지만 여기는 그냥 죽은 정책 행이다 —
--    해석기(NotificationRoutingPolicy)가 enum에 없는 코드를 조용히 무시한다.
--
-- 그래서 엔티티도 이 컬럼을 String으로 든다(@Enumerated였다면 모르는 코드 한 행이 조회를
-- 통째로 터뜨리고, 위 대조 테스트가 CHECK를 요구한다). app_cd는 반대로 enum이며 CHECK가 있다 —
-- 앱은 셋뿐이고 늘어날 일이 사실상 배포 단위의 사건이다.
--
-- ── test 프로필은 이 파일을 읽지 않는다 ────────────────────────────────────
-- V3·V11·V16·V19처럼 spring.sql.init.data-locations에 얹는 길을 검토했으나 택하지 않았다.
-- 이 파일은 DDL이 섞여 있어(IDENTITY·DO $$) H2에서 돌지 않고, DDL과 시드를 두 파일로 쪼개
-- 시드만 얹으면 «표가 비어 있다 = 보낸 앱»이라는 기본 경로가 어느 테스트에서도 안 밟힌다.
-- 테스트는 빈 표에서 출발해 필요한 행을 리포지토리로 직접 넣고, **시드 자체는 실제
-- PostgreSQL을 든 FlywayMigrationValidateTest가 대조한다**(referenceDataIsSeededByMigration 옆).
--
-- 표준 단어(데이터사전 · ssccops#450): 알림 noti · 유형 type · 수신 rcpn · 앱 app ·
-- 코드 cd · 등록 reg · 수정 upd · 일시 dt.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."noti_type_rcpn" (
    "noti_type_rcpn_id" bigint NOT NULL,
    -- NotificationType의 이름. CHECK를 걸지 않는다 — 위 주석 참고
    "noti_type_cd" character varying(30) NOT NULL,
    -- ADMIN · LMS · WWW (NotificationApp)
    "app_cd" character varying(20) NOT NULL,
    "reg_dt" timestamp(6) with time zone NOT NULL,
    "upd_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "noti_type_rcpn_app_cd_check"
        CHECK ((("app_cd")::"text" = ANY ((ARRAY[
            'ADMIN'::character varying,
            'LMS'::character varying,
            'WWW'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'noti_type_rcpn'
                      AND "column_name" = 'noti_type_rcpn_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."noti_type_rcpn"
            ALTER COLUMN "noti_type_rcpn_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."noti_type_rcpn_noti_type_rcpn_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'noti_type_rcpn_pkey') THEN
        ALTER TABLE ONLY "public"."noti_type_rcpn"
            ADD CONSTRAINT "noti_type_rcpn_pkey" PRIMARY KEY ("noti_type_rcpn_id");
    END IF;
    -- 같은 유형을 같은 앱에 두 번 등록하지 않는다. 수정 API가 «지우고 다시 넣는다»라
    -- 이 제약이 곧 중복 방지의 전부다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_noti_type_rcpn') THEN
        ALTER TABLE ONLY "public"."noti_type_rcpn"
            ADD CONSTRAINT "uk_noti_type_rcpn" UNIQUE ("noti_type_cd", "app_cd");
    END IF;
END $$;

-- 해석기는 표를 통째로 읽어 캐시하지만, 앱 하나로 좁히는 조회(어느 유형이 이 앱에 오는가)가
-- 캐시를 못 쓰는 자리에서 돌 수 있다. 36행짜리 표라 비용이 아니라 의도의 표시에 가깝다
CREATE INDEX IF NOT EXISTS "idx_noti_type_rcpn_app"
    ON "public"."noti_type_rcpn" ("app_cd");

-- ── 시드 — 지금 12종을 **현재 동작 그대로** ────────────────────────────────
--
-- 운영 5종은 어드민의 하위 업무 라우트로 가는 알림이고, 회원 6종은 «내가 낸 것의 처리 과정»이라
-- www가 허브다(#528의 판단 그대로). 즉 이 시드는 정책을 바꾸지 않는다 — 표가 서기 전의 동작을
-- 표로 옮겨 적은 것이고, 바꾸는 것은 이제 어드민 화면의 일이다.
--
-- **TEST는 시드하지 않는다.** 테스트 알림의 수신 앱은 «누른 앱»이라 행마다 달라야 하는데,
-- 그것이 정확히 미등록의 기본값(보낸 앱)이다. 여기에 세 앱을 다 넣으면 admin에서 누른 확인
-- 알림이 www 목록에도 뜬다.
--
-- 멱등 가드(WHERE NOT EXISTS)는 V11이 세운 규칙이다 — 운영진이 화면에서 고친 값을 재실행이
-- 되돌리지 않는다. 그래서 «행이 있으면 건드리지 않는다»이지 UPDATE가 아니다.
INSERT INTO "public"."noti_type_rcpn" ("noti_type_cd", "app_cd", "reg_dt", "upd_dt")
SELECT v.noti_type_cd, v.app_cd, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
    ('APPROVAL_REQUESTED', 'ADMIN'),
    ('APPROVAL_APPROVED', 'ADMIN'),
    ('APPROVAL_REJECTED', 'ADMIN'),
    ('DEADLINE_DUE', 'ADMIN'),
    ('DEADLINE_OVERDUE', 'ADMIN'),
    ('RESPONSE_ACCEPTED', 'WWW'),
    ('RESPONSE_REJECTED', 'WWW'),
    ('RESPONSE_CHANGES_REQUESTED', 'WWW'),
    ('APPLICATION_CONFIRMED', 'WWW'),
    ('APPLICATION_WAITLISTED', 'WWW'),
    ('APPLICATION_CANCELLED', 'WWW')
) AS v (noti_type_cd, app_cd)
WHERE NOT EXISTS (
    SELECT 1 FROM "public"."noti_type_rcpn" x
     WHERE x."noti_type_cd" = v.noti_type_cd AND x."app_cd" = v.app_cd);
