-- ============================================================================
-- V28 — 행사 참가 상태 이력 (event_ptcp_stts_hstry)
-- ============================================================================
-- #612 · ssccops#553 · ADR-0042(자유도를 열면 이력을 붙인다).
--
-- 스터디장이 팀원을 넣고 빼게 되면서(POST·PATCH /v1/academic-programs/{id}/members) 명단
-- (event_ptcp)을 바꾸는 길이 셋이 됐다 — 행사 참가자 API · 학술 모집 선발 · 학술 팀원 관리.
-- 그전까지 남는 것은 event_ptcp.mdfcn_dt 하나라 «언제 누가 어느 화면에서 뺐나»에 답할 수 없었다.
-- **세 경로가 모두** 이 표에 한 줄씩 남긴다(EventParticipationServiceImpl.recordStatusChange).
--
-- 어휘는 sub_work_stts_hstry를 따른다(bfr_·aftr_ · prfmr_id · chg_dt). 등록(처음 명단에 오름)도
-- 한 줄이라 bfr_ptcp_stts_cd는 NULL을 허용한다. 전 컬럼 불변이다(엔티티가 updatable = false).
--
-- FK 둘의 삭제 규칙이 다르다 — 그것이 회원 하드 삭제(ADR-0021)의 경계다.
--   event_ptcp_id → event_ptcp  ON DELETE CASCADE
--       참가 행이 회원 삭제로 지워지면(V9) 그 행의 이력도 뜻을 잃는다. atndc.event_ptcp_id와 같다.
--   prfmr_id      → mbr         NO ACTION (행위자 참조)
--       남의 참가 상태를 바꾼 회원은 하드 삭제가 막힌다. MemberReferenceConstraints가 이 제약
--       이름(fk_event_ptcp_stts_hstry_prfmr)을 사람 표기로 번역한다 — 이름을 바꾸면 그 표도 고친다.
--
-- 기존 참가 행에 대한 이력은 채우지 않는다 — 언제 누가 올렸는지(crt_dt · rgtr_mbr_id)는 있지만
-- 그 뒤의 변경은 남아 있지 않아, 채우면 «등록 한 줄»만 있는 불완전한 이력이 사실처럼 보인다.
-- 이력은 이 마이그레이션 이후의 변경부터다.
--
-- 코드값은 enum의 사본이다 — 정본은 EventParticipantStatus · EventParticipantChangePath이고
-- FlywayMigrationValidateTest.checkConstraintsMatchTheirEnums가 대조한다.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."event_ptcp_stts_hstry" (
    "event_ptcp_stts_hstry_id" bigint NOT NULL,
    "event_ptcp_id" bigint NOT NULL,
    -- 처음 명단에 오른 등록이면 NULL
    "bfr_ptcp_stts_cd" character varying(20),
    "aftr_ptcp_stts_cd" character varying(20) NOT NULL,
    "prfmr_id" bigint NOT NULL,
    -- EVENT_PARTICIPANTS · RECRUITMENT_SELECTION · TEAM_MEMBERS (EventParticipantChangePath)
    "chg_path_se_cd" character varying(20) NOT NULL,
    "chg_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "event_ptcp_stts_hstry_bfr_ptcp_stts_cd_check"
        CHECK ((("bfr_ptcp_stts_cd")::"text" = ANY ((ARRAY[
            'CONFIRMED'::character varying,
            'WAITLISTED'::character varying,
            'CANCELLED'::character varying])::"text"[]))),
    CONSTRAINT "event_ptcp_stts_hstry_aftr_ptcp_stts_cd_check"
        CHECK ((("aftr_ptcp_stts_cd")::"text" = ANY ((ARRAY[
            'CONFIRMED'::character varying,
            'WAITLISTED'::character varying,
            'CANCELLED'::character varying])::"text"[]))),
    CONSTRAINT "event_ptcp_stts_hstry_chg_path_se_cd_check"
        CHECK ((("chg_path_se_cd")::"text" = ANY ((ARRAY[
            'EVENT_PARTICIPANTS'::character varying,
            'RECRUITMENT_SELECTION'::character varying,
            'TEAM_MEMBERS'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'event_ptcp_stts_hstry'
                      AND "column_name" = 'event_ptcp_stts_hstry_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."event_ptcp_stts_hstry"
            ALTER COLUMN "event_ptcp_stts_hstry_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."event_ptcp_stts_hstry_event_ptcp_stts_hstry_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'event_ptcp_stts_hstry_pkey') THEN
        ALTER TABLE ONLY "public"."event_ptcp_stts_hstry"
            ADD CONSTRAINT "event_ptcp_stts_hstry_pkey" PRIMARY KEY ("event_ptcp_stts_hstry_id");
    END IF;
    -- 참가 행에 딸린 이력 — 참가 행이 지워지면 함께 지워진다 (V9 · ADR-0021 · atndc와 같다)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint"
                    WHERE "conname" = 'fk_event_ptcp_stts_hstry_event_ptcp') THEN
        ALTER TABLE ONLY "public"."event_ptcp_stts_hstry"
            ADD CONSTRAINT "fk_event_ptcp_stts_hstry_event_ptcp"
            FOREIGN KEY ("event_ptcp_id") REFERENCES "public"."event_ptcp"("event_ptcp_id")
            ON DELETE CASCADE;
    END IF;
    -- 행위자 참조 — cascade가 없다. 회원 하드 삭제를 막는다(MemberReferenceConstraints)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint"
                    WHERE "conname" = 'fk_event_ptcp_stts_hstry_prfmr') THEN
        ALTER TABLE ONLY "public"."event_ptcp_stts_hstry"
            ADD CONSTRAINT "fk_event_ptcp_stts_hstry_prfmr"
            FOREIGN KEY ("prfmr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

-- 학술 팀원 이력 조회가 행사의 참가 행들로 이 표를 찾는다
CREATE INDEX IF NOT EXISTS "idx_event_ptcp_stts_hstry_event_ptcp_id"
    ON "public"."event_ptcp_stts_hstry" ("event_ptcp_id");
