-- ============================================================================
-- V29 — 업무 태그 (work_tag · work_tag_rel)
-- ============================================================================
-- #624 · ssccops#565.
--
-- 운영진이 업무명 앞에 «학술국»을 적어 구분하던 것을 태그로 옮긴다. 주관 국도 태그로 쓴다
-- (별도 칸 없음 · 2026-10-03 QnA). 모양은 폼 라벨(form_lbl · form_lbl_rel)을 본뜬다 —
-- 태그 목록은 따로 관리하고, 업무에는 고르기만 하며, 지정은 전체 교체다.
--
-- **폼 라벨 표를 공유하지 않는다.** 폼 라벨은 FORM_LABEL_MANAGE가 관리하고 목록도 다르다 —
-- 공유하면 «폼 라벨 목록에 학술국이 왜 있나»가 된다.
--
-- 폼 라벨과 갈리는 자리 둘:
--   use_yn이 없다    — 태그는 지우면 관계도 함께 지운다(업무는 그대로). 폼 라벨은 과거 폼의
--                      분류를 지키려 비활성으로만 내리지만, 업무 태그는 «지금 어느 국 일인가»를
--                      거르는 꼬리표라 지운 태그가 남아 있을 이유가 없다(ssccops#565 수용 기준).
--   이름을 바꿀 수 있다 — 국 이름이 바뀌면 태그 이름도 따라 바뀌어야 한다. 폼 라벨은 이름 변경을
--                      범위에 넣지 않았다(FormLabelUpdateRequest 주석).
--
-- 이름은 데이터사전 표준단어다 — 태그 = TAG(공공표준단어 8차), 업무 = WORK, 관계 = REL, 명 = NM.
--
-- FK 둘의 삭제 규칙이 다르다.
--   work_tag_id → work_tag  ON DELETE CASCADE
--       태그를 지우면 그 태그의 지정도 뜻을 잃는다. 서비스(WorkTagServiceImpl.deleteTag)도 먼저
--       지우지만, DB가 같은 규칙을 갖고 있어야 다른 경로(수동 정리)에서도 고아가 남지 않는다.
--   work_id     → work      NO ACTION
--       업무는 소프트 삭제(oper.del_dt)라 work 행이 지워지는 일이 없다. 지워지는 날이 오면
--       그때 이 규칙을 다시 정한다.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."work_tag" (
    "work_tag_id" bigint NOT NULL,
    "tag_nm" character varying(50) NOT NULL,
    "crt_dt" timestamp(6) with time zone NOT NULL,
    "mdfcn_dt" timestamp(6) with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."work_tag_rel" (
    "work_tag_rel_id" bigint NOT NULL,
    "work_id" bigint NOT NULL,
    "work_tag_id" bigint NOT NULL,
    -- 이 업무에 태그가 달린 시각. 지정 교체가 유지되는 연결을 다시 만들지 않아 보존된다
    "crt_dt" timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'work_tag'
                      AND "column_name" = 'work_tag_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."work_tag"
            ALTER COLUMN "work_tag_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."work_tag_work_tag_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'work_tag_rel'
                      AND "column_name" = 'work_tag_rel_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."work_tag_rel"
            ALTER COLUMN "work_tag_rel_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."work_tag_rel_work_tag_rel_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'work_tag_pkey') THEN
        ALTER TABLE ONLY "public"."work_tag"
            ADD CONSTRAINT "work_tag_pkey" PRIMARY KEY ("work_tag_id");
    END IF;
    -- 이름이 사람이 태그를 고르는 유일한 단서다 — 선조회로는 동시 생성을 못 막아 DB에 둔다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_work_tag_name') THEN
        ALTER TABLE ONLY "public"."work_tag"
            ADD CONSTRAINT "uk_work_tag_name" UNIQUE ("tag_nm");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'work_tag_rel_pkey') THEN
        ALTER TABLE ONLY "public"."work_tag_rel"
            ADD CONSTRAINT "work_tag_rel_pkey" PRIMARY KEY ("work_tag_rel_id");
    END IF;
    -- 같은 태그를 같은 업무에 두 번 달면 칩이 두 번 뜨고 사용 건수가 부푼다 (form_lbl_rel과 같다)
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_work_tag_rel_work_tag') THEN
        ALTER TABLE ONLY "public"."work_tag_rel"
            ADD CONSTRAINT "uk_work_tag_rel_work_tag" UNIQUE ("work_id", "work_tag_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_work_tag_rel_work') THEN
        ALTER TABLE ONLY "public"."work_tag_rel"
            ADD CONSTRAINT "fk_work_tag_rel_work"
            FOREIGN KEY ("work_id") REFERENCES "public"."work"("work_id");
    END IF;
    -- 태그를 지우면 지정도 함께 지워진다 — 업무는 그대로다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_work_tag_rel_work_tag') THEN
        ALTER TABLE ONLY "public"."work_tag_rel"
            ADD CONSTRAINT "fk_work_tag_rel_work_tag"
            FOREIGN KEY ("work_tag_id") REFERENCES "public"."work_tag"("work_tag_id")
            ON DELETE CASCADE;
    END IF;
END $$;

-- 업무 목록의 태그 필터가 태그 쪽에서 관계를 찾는다. (work_id, work_tag_id) UNIQUE는 업무 쪽만 덮는다
CREATE INDEX IF NOT EXISTS "idx_work_tag_rel_work_tag_id"
    ON "public"."work_tag_rel" ("work_tag_id");
