-- ============================================================================
-- V2 — 공유 링크 테이블 (shr_lnk)
-- ============================================================================
-- baseline(V1)이 prod 덤프인데 prod에는 이 테이블이 없다 — prod는 `main`에서 배포되고
-- 공유 링크(ssccops#200)는 아직 `develop`에만 있기 때문이다. dev에는 이미 있다.
--
-- 그래서 **두 환경에서 결과가 달라야 하는 유일한 마이그레이션이다.** dev에서는 아무 일도
-- 일어나지 않고, prod는 다음 릴리스에 이것으로 테이블을 얻는다. 그 뒤로 둘은 같은 모양이다.
--
-- 통째로 하나의 DO 블록인 것은 `ADD CONSTRAINT`와 `ADD GENERATED`에 `IF NOT EXISTS`가 없기
-- 때문이다. 테이블이 있으면(dev) 전부 건너뛰고 없으면(prod·새 DB) 전부 만든다 — 반쯤 만들어진
-- 상태는 존재하지 않으므로 이 판정 하나면 충분하다.
--
-- 제약 이름은 dev에 이미 붙어 있는 것(Hibernate가 지은 이름 포함)을 그대로 쓴다. 읽기 좋은
-- 이름으로 바꾸면 두 환경의 제약 이름이 갈리고, 그 차이는 다음에 스키마를 대조할 때마다 노이즈가 된다.
--
-- 컬럼 정의는 `document/dev.sql`의 실제 정의와 `ShareLinkEntity`를 대조해 맞췄다 —
-- `shr_tkn varchar(50)`(ssccops#212에서 64→50) · `shr_trgt_se_cd`(개명 후 이름) ·
-- `rvk_dt` nullable(NULL이면 살아 있는 링크다).
-- ============================================================================

DO $$
BEGIN
    IF to_regclass('public.shr_lnk') IS NOT NULL THEN
        RETURN;
    END IF;

    CREATE TABLE "public"."shr_lnk" (
        "shr_lnk_id" bigint NOT NULL,
        "crt_dt" timestamp(6) with time zone NOT NULL,
        "rvk_dt" timestamp(6) with time zone,
        "trgt_id" bigint NOT NULL,
        "shr_tkn" character varying(50) NOT NULL,
        "mdfcn_dt" timestamp(6) with time zone NOT NULL,
        "iss_mbr_id" bigint NOT NULL,
        "shr_trgt_se_cd" character varying(20) NOT NULL,
        CONSTRAINT "shr_lnk_shr_trgt_se_cd_check"
            CHECK ((("shr_trgt_se_cd")::"text" = 'SUB_WORK'::"text"))
    );

    ALTER TABLE "public"."shr_lnk" ALTER COLUMN "shr_lnk_id"
        ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME "public"."shr_lnk_shr_lnk_id_seq"
            START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
        );

    ALTER TABLE ONLY "public"."shr_lnk"
        ADD CONSTRAINT "shr_lnk_pkey" PRIMARY KEY ("shr_lnk_id");

    ALTER TABLE ONLY "public"."shr_lnk"
        ADD CONSTRAINT "uk_shr_lnk_tkn" UNIQUE ("shr_tkn");

    ALTER TABLE ONLY "public"."shr_lnk"
        ADD CONSTRAINT "fklls20mda396fxtj1ts4p7db5i"
            FOREIGN KEY ("iss_mbr_id") REFERENCES "public"."mbr"("mbr_id");
END $$;
