-- ============================================================================
-- V31 — 태그를 운영 건 단위로 옮긴다 (oper_tag · oper_tag_rel)
-- ============================================================================
-- #637 · ssccops#576.
--
-- V29(#624)는 태그를 상위 업무(work)에만 달았다. 업무·하위 업무·회의는 모두 oper의 확장이라
-- 태그를 oper에 두면 셋이 같은 태그 목록을 쓰고, 운영 통합(/v1/operations)이 행마다 같은 기준으로
-- 칩·필터를 그린다(운영진 결정 · 2026-10-03). 릴리스 전(prod는 V28)이라 옮길 데이터는 dev뿐이다.
--
-- **V29는 고치지 않는다** — dev에 이미 적용돼 체크섬이 박혀 있다. 대신 새 표를 만들고 옮긴 뒤 옛
-- 표를 지운다. RENAME + ALTER로도 되지만, 제약·시퀀스·인덱스 이름 일곱 개를 하나씩 바꾸는 것보다
-- 새로 만드는 쪽이 결과 스키마를 이 파일 하나로 읽을 수 있다.
--
-- 이름은 데이터사전 표준단어다 — 운영 = OPER, 태그 = TAG, 관계 = REL, 명 = NM.
--   oper_tag      운영_태그       (oper_tag_id · tag_nm · crt_dt · mdfcn_dt)
--   oper_tag_rel  운영_태그_관계  (oper_tag_rel_id · oper_id · oper_tag_id · crt_dt)
--
-- 제약 모양은 V29 그대로다 — 이름 UNIQUE · (운영 건, 태그) UNIQUE · 태그 삭제 시 지정 CASCADE ·
-- 태그 쪽 인덱스. oper_id → oper는 NO ACTION이다: 운영 건은 소프트 삭제(oper.del_dt)라 oper 행이
-- 지워지는 일이 없다.
--
-- 데이터 이관: 태그는 식별자 그대로, 지정은 work_id → 그 업무의 work.oper_id. 식별자를 유지하므로
-- 시퀀스를 최댓값 뒤로 옮겨 둔다. 옛 표가 없는 DB(빈 DB에서 처음부터 돌 때도 V29가 먼저 만들므로
-- 보통은 있다)에서도 깨지지 않게 to_regclass로 확인한다.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."oper_tag" (
    "oper_tag_id" bigint NOT NULL,
    "tag_nm" character varying(50) NOT NULL,
    "crt_dt" timestamp(6) with time zone NOT NULL,
    "mdfcn_dt" timestamp(6) with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."oper_tag_rel" (
    "oper_tag_rel_id" bigint NOT NULL,
    "oper_id" bigint NOT NULL,
    "oper_tag_id" bigint NOT NULL,
    -- 이 운영 건에 태그가 달린 시각. 지정 교체가 유지되는 연결을 다시 만들지 않아 보존된다
    "crt_dt" timestamp(6) with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'oper_tag'
                      AND "column_name" = 'oper_tag_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."oper_tag"
            ALTER COLUMN "oper_tag_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."oper_tag_oper_tag_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public' AND "table_name" = 'oper_tag_rel'
                      AND "column_name" = 'oper_tag_rel_id' AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."oper_tag_rel"
            ALTER COLUMN "oper_tag_rel_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."oper_tag_rel_oper_tag_rel_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'oper_tag_pkey') THEN
        ALTER TABLE ONLY "public"."oper_tag"
            ADD CONSTRAINT "oper_tag_pkey" PRIMARY KEY ("oper_tag_id");
    END IF;
    -- 이름이 사람이 태그를 고르는 유일한 단서다 — 선조회로는 동시 생성을 못 막아 DB에 둔다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_oper_tag_name') THEN
        ALTER TABLE ONLY "public"."oper_tag"
            ADD CONSTRAINT "uk_oper_tag_name" UNIQUE ("tag_nm");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'oper_tag_rel_pkey') THEN
        ALTER TABLE ONLY "public"."oper_tag_rel"
            ADD CONSTRAINT "oper_tag_rel_pkey" PRIMARY KEY ("oper_tag_rel_id");
    END IF;
    -- 같은 태그를 같은 운영 건에 두 번 달면 칩이 두 번 뜨고 사용 건수가 부푼다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'uk_oper_tag_rel_oper_tag') THEN
        ALTER TABLE ONLY "public"."oper_tag_rel"
            ADD CONSTRAINT "uk_oper_tag_rel_oper_tag" UNIQUE ("oper_id", "oper_tag_id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_oper_tag_rel_oper') THEN
        ALTER TABLE ONLY "public"."oper_tag_rel"
            ADD CONSTRAINT "fk_oper_tag_rel_oper"
            FOREIGN KEY ("oper_id") REFERENCES "public"."oper"("oper_id");
    END IF;
    -- 태그를 지우면 지정도 함께 지워진다 — 운영 건은 그대로다
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint" WHERE "conname" = 'fk_oper_tag_rel_oper_tag') THEN
        ALTER TABLE ONLY "public"."oper_tag_rel"
            ADD CONSTRAINT "fk_oper_tag_rel_oper_tag"
            FOREIGN KEY ("oper_tag_id") REFERENCES "public"."oper_tag"("oper_tag_id")
            ON DELETE CASCADE;
    END IF;
END $$;

-- 목록·운영 통합의 태그 필터가 태그 쪽에서 관계를 찾는다. (oper_id, oper_tag_id) UNIQUE는 운영 건 쪽만 덮는다
CREATE INDEX IF NOT EXISTS "idx_oper_tag_rel_oper_tag_id"
    ON "public"."oper_tag_rel" ("oper_tag_id");

-- ----------------------------------------------------------------------------
-- dev 데이터 이관 — 태그는 그대로, 지정은 업무의 oper_id로. 다시 돌아도 같은 결과다(ON CONFLICT)
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF to_regclass('public.work_tag') IS NOT NULL THEN
        INSERT INTO "public"."oper_tag" ("oper_tag_id", "tag_nm", "crt_dt", "mdfcn_dt")
        SELECT "work_tag_id", "tag_nm", "crt_dt", "mdfcn_dt"
          FROM "public"."work_tag"
        ON CONFLICT DO NOTHING;
    END IF;
    IF to_regclass('public.work_tag_rel') IS NOT NULL THEN
        INSERT INTO "public"."oper_tag_rel" ("oper_tag_rel_id", "oper_id", "oper_tag_id", "crt_dt")
        SELECT r."work_tag_rel_id", w."oper_id", r."work_tag_id", r."crt_dt"
          FROM "public"."work_tag_rel" r
          JOIN "public"."work" w ON w."work_id" = r."work_id"
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- 식별자를 그대로 옮겼으므로 다음 발급이 옮긴 값과 겹치지 않게 시퀀스를 최댓값 뒤로 둔다
SELECT setval('"public"."oper_tag_oper_tag_id_seq"',
              COALESCE((SELECT MAX("oper_tag_id") FROM "public"."oper_tag"), 0) + 1, false);
SELECT setval('"public"."oper_tag_rel_oper_tag_rel_id_seq"',
              COALESCE((SELECT MAX("oper_tag_rel_id") FROM "public"."oper_tag_rel"), 0) + 1, false);

-- 옛 표를 지운다 — 관계가 태그를 가리키므로 관계부터. 시퀀스는 IDENTITY 소유라 함께 사라진다
DROP TABLE IF EXISTS "public"."work_tag_rel";
DROP TABLE IF EXISTS "public"."work_tag";
