-- ============================================================================
-- V5 — 하위 업무 점검 목록 이력 테이블 (sub_work_chck_list_hstry)
-- ============================================================================
-- #307이 완료 체크리스트 항목의 추가·수정·삭제를 열면서 함께 만드는 테이블이다.
--
-- **이 테이블이 그 개방의 조건이다.** 항목 편집을 기획·진행으로 좁히고(검토부터 잠근다)
-- 체크된 항목의 삭제를 막아도, 기획·진행 단계에서 항목을 지우는 것은 여전히 가능하고 그건
-- 정당한 행동이다. 무엇이 지워졌는지 아무 데도 남지 않으면 나중에 "이 업무는 왜 점검 항목이
-- 셋뿐이었나"에 답할 수 없다 (ssccops#255 결정 코멘트).
--
-- 컬럼 표기는 sub_work_stts_hstry를 그대로 따랐다 — 전/후 값에 bfr_·aftr_, 수행자는 prfmr_id,
-- 시각은 chg_dt다. 두 이력을 나란히 읽는 자리가 생기므로 어휘가 갈리면 안 된다.
--
-- **sub_work_chck_list_id에 FK가 없다.** 삭제를 하드로 하기로 했기 때문이다 — 소프트 삭제는
-- sub_work_chck_list를 읽는 세 자리(목록·미완료 개수·진행률 집계)에 필터를 하나씩 더 요구하고
-- 그중 하나만 빠뜨리면 지워진 항목이 영영 완료를 막는다. 이력이 따로 남으므로 하드로 지워도
-- 흔적이 사라지지 않고, 그 대신 이 컬럼은 이미 없는 행을 가리킬 수 있다.
--
-- 제약·식별자 이름은 읽을 수 있는 이름으로 직접 짓는다. V2가 Hibernate가 지은 이름을 그대로
-- 옮겨 쓴 것은 dev에 이미 그 이름으로 붙어 있었기 때문이고, 이 테이블은 어느 환경에도 아직
-- 없으므로 그 제약이 없다.
--
-- 새 테이블이라 `local`(ddl-auto: update)에서는 Hibernate도 만들 수 있지만, 그때 붙는 제약
-- 이름이 여기와 달라져 환경 간 스키마가 갈린다. `IF NOT EXISTS`로 두어 어느 쪽이 먼저 만들든
-- 두 번 만들지 않게 한다.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."sub_work_chck_list_hstry" (
    "sub_work_chck_list_hstry_id" bigint NOT NULL,
    "sub_work_id" bigint NOT NULL,
    -- 대상 항목. 삭제된 항목도 가리키므로 FK가 아니다 (위 주석)
    "sub_work_chck_list_id" bigint NOT NULL,
    -- ADDED · MODIFIED · REMOVED (ChecklistChangeType)
    "chck_chg_se_cd" character varying(20) NOT NULL,
    -- 추가는 이전 문구가 없고, 삭제된 항목의 마지막 문구가 여기 남는다
    "bfr_chck_artcl_cn" "text",
    -- 삭제는 이후 문구가 없다
    "aftr_chck_artcl_cn" "text",
    "prfmr_id" bigint NOT NULL,
    "chg_dt" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "sub_work_chck_list_hstry_chck_chg_se_cd_check"
        CHECK ((("chck_chg_se_cd")::"text" = ANY ((ARRAY[
            'ADDED'::character varying,
            'MODIFIED'::character varying,
            'REMOVED'::character varying])::"text"[])))
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "information_schema"."columns"
                    WHERE "table_schema" = 'public'
                      AND "table_name" = 'sub_work_chck_list_hstry'
                      AND "column_name" = 'sub_work_chck_list_hstry_id'
                      AND "is_identity" = 'YES') THEN
        ALTER TABLE "public"."sub_work_chck_list_hstry"
            ALTER COLUMN "sub_work_chck_list_hstry_id"
            ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME "public"."sub_work_chck_list_hstry_sub_work_chck_list_hstry_id_seq"
                START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
            );
    END IF;
END $$;

-- ADD CONSTRAINT·CREATE INDEX 중 앞의 둘에는 IF NOT EXISTS가 없어 존재 여부를 직접 본다.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "pg_constraint"
                    WHERE "conname" = 'sub_work_chck_list_hstry_pkey') THEN
        ALTER TABLE ONLY "public"."sub_work_chck_list_hstry"
            ADD CONSTRAINT "sub_work_chck_list_hstry_pkey"
            PRIMARY KEY ("sub_work_chck_list_hstry_id");
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "pg_constraint"
                    WHERE "conname" = 'fk_sub_work_chck_list_hstry_sub_work') THEN
        ALTER TABLE ONLY "public"."sub_work_chck_list_hstry"
            ADD CONSTRAINT "fk_sub_work_chck_list_hstry_sub_work"
            FOREIGN KEY ("sub_work_id") REFERENCES "public"."sub_work"("sub_work_id");
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "pg_constraint"
                    WHERE "conname" = 'fk_sub_work_chck_list_hstry_prfmr') THEN
        ALTER TABLE ONLY "public"."sub_work_chck_list_hstry"
            ADD CONSTRAINT "fk_sub_work_chck_list_hstry_prfmr"
            FOREIGN KEY ("prfmr_id") REFERENCES "public"."mbr"("mbr_id");
    END IF;
END $$;

-- 이력 조회는 언제나 하위 업무 하나를 축으로 한다. PostgreSQL은 FK에 인덱스를 자동으로
-- 만들지 않으므로 직접 건다 (DB-17 · sub_work의 idx_sub_work_work_id와 같은 이유).
CREATE INDEX IF NOT EXISTS "idx_sub_work_chck_list_hstry_sub_work_id"
    ON "public"."sub_work_chck_list_hstry" ("sub_work_id");
